# Generated by Django 3.1.7 on 2021-03-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210318_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
